### PR TITLE
Move ids to top of reference objects

### PR DESCRIPTION
**Pull request by RobertDeRose**

### CODE REVIEW

**Comment by yoshizzle** [comment]
Looks good, but just curious as to why?

**Comment by RobertDeRose** [comment]
If you remember there was a comment that "it kind of sucks" that the id's didn't show up at the top of the object as one might expect.  The only thing that stopped that was the placement in the yaml file, so I just did it.

**Comment by RobertDeRose** [comment]
@Dorthu Can I get a little merge love here?

**Comment by RobertDeRose** [comment]
@Dorthu or @jamesottinger wanna give this some merging love before I have to rebase like for the 20th time?

**Comment by jamesottinger** [comment]
I got you @RobertDeRose

**Pull request merged**
