### PR TITLE
API v4.93.0 Changelog

### PR DESCRIPTION
**Pull request by bbiggerr**

### CODE REVIEW

**Review by yoshizzle — APPROVED** [review]
@bbiggerr are the added filterable params something we don't typically include?

**Comment by bbiggerr** [comment]
> @bbiggerr are the added filterable params something we don't typically include?

They should be included -- I added them under "Changed"

**Comment by alsaihn** [comment]
Is this missing the stackscript addition, or am I not seeing it?

**Comment by bbiggerr** [comment]
> Is this missing the stackscript addition, or am I not seeing it?

It is! Thank you, adding now

**Review by alsaihn — APPROVED** [review]

**Pull request merged**
