### PR TITLE
API 4.62.0 release changelog

### PR DESCRIPTION
**Pull request by leslitagordita**

### CODE REVIEW

**Review by alsaihn — APPROVED** [review]
lgtm, but should be vetted by the LKE team also. Thanks!

**Comment by adammohammed** [comment]
We also [removed filterable](https://github.com/linode/linode-api-docs/pull/242/files#diff-fe030a7c1568b3decf599edf399be7f4L15760) on "k8s-version". 

And corrected the [LkeNodeStatus schema](https://github.com/linode/linode-api-docs/pull/242/files#diff-fe030a7c1568b3decf599edf399be7f4R15886)

**Comment by leslitagordita** [comment]
@adammohammed updated!

**Review by adammohammed — APPROVED** [review]
Looks good!

**Pull request merged**
