### PR TITLE
Include Jekyll-Liverealod

### PR DESCRIPTION
**Pull request by RobertDeRose**
Github's guide on setting up Github-Pages for local development uses
`bundler`. We should not deviate from that. Also included
`Jekyll-Livereload` plugin and configured it to run by default.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
We'll be moving this away from GitHub pages in the future and just using jekyll straight up on some of our own servers. We should suggest the Jekyll way of setting this up: https://jekyllrb.com/docs/installation/

The only difference is that we suggest using `gem install github-pages` instead of `gem install jekyll` to make sure you get the version of Jekyll and such that GitHub is using, since we *presently* are on GitHub pages.

**Comment by RobertDeRose** [comment]
@SirCmpwn Using Bundler is still a pretty common practice for using Jekyll because it is pretty common way to include plugins.  Plus the focus on this was to include the Livereload plugin.

**Comment by SirCmpwn** [comment]
>If we are "going to" move to straight Jekyll, that's fine, but while we are using Github-Pages we should stay inline with best practices or remove the link to the Github guide.

I favor the latter solution.

**Comment by Dorthu** [comment]
fwiw I think this warrants further discussion.

**Pull request closed without merging**
