### PR TITLE
Added FAQ page and links

### PR DESCRIPTION
**Pull request by yoshizzle**
Someone will probably have to come in behind this commit and do
some better styling, but for now it has the essentials.

### CODE REVIEW

**Comment by yoshizzle** [comment]
https://linode.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=API&view=detail&selectedIssue=API-377

**Comment by eatonphil** [comment]
Could you post a screenshot?

**Comment by Dorthu** [comment]
Screenshots:

screen shot 2016-05-04 at 11 24 04 am
screen shot 2016-05-04 at 11 24 20 am

**Comment by eatonphil** [comment]
Cool, thank you

**Pull request merged**
